import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: {
    default: "Next Hero",
    template: "Next hero | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Navbar></Navbar>

        {children}

        <div className="block bg-blue-600 py-3 text-white font-semibold text-center">
          this is footer
        </div>

      </body>
    </html>
  );
}
